
- name: Ensure group "{{ zabbix_group }}" exists
  group: 
    name: "{{ zabbix_group }}"
    state: present
    system: yes

- name: Add the user "{{ zabbix_user }}" with a primary group of "{{ zabbix_group }}" and a nologin shell
  user: 
    name: "{{ zabbix_user }}"
    group: "{{ zabbix_group }}"
    shell: /sbin/nologin
    comment: "Zabbix Monitoring System"
    create_home: no
    home: /var/lib/zabbix

- name: Copy the source archive of zabbix into "{{ zabbix_source_dir }}".
  copy: 
    src: zabbix-{{ zabbix_version }}.tar.gz 
    dest: "{{ zabbix_source_dir }}"
    owner: root
    group: root
    mode: 0644

- name: Extract the source archive of zabbix
  unarchive: 
    src: "{{ zabbix_source_dir }}/zabbix-{{ zabbix_version }}.tar.gz"
    dest: "{{ zabbix_source_dir }}"
    remote_src: yes
    owner: root
    group: root
    creates: "{{ zabbix_source_dir }}/zabbix-{{ zabbix_version }}"

- name: Compile and install zabbix  #? ipv6 tls
  shell: ./configure --prefix={{ zabbix_basedir }} --enable-agent --with-openssl && make -j $(nproc) && make install
  args: 
    chdir: "{{ zabbix_source_dir }}/zabbix-{{ zabbix_version }}"
    creates: "{{ zabbix_basedir }}"

# - name: Create a soft link from zabbix-{{ zabbix_version }} to zabbix
#   file: 
#     src: "{{ zabbix_basedir }}-{{ zabbix_version }}"
#     dest: "{{ zabbix_basedir }}"
#     state: link

# - name: Update zabbix agent default configure file "zabbix_agentd.conf" 
#   template: 
#     src: zabbix_agentd.conf.j2
#     dest: "{{ zabbix_basedir }}/etc/zabbix_agentd.conf"
