---
- name: Config service with initd.
  template: 
    src: init.d/zabbix_agentd.j2
    dest: "{{ init_script }}"
    owner: root
    group: root
    mode: 0755
  when: use_initd

- name: Config service with systemd.
  template: 
    src: systemd/zabbix_agentd.service.j2
    dest: "{{ sysd_script }}"
    owner: root
    group: root
    mode: 0755
  when: use_systemd

- name: Service | Enable and start "{{ zabbix_agentd_service }}"
  service: 
    name: "{{ zabbix_agentd_service }}"
    enabled: yes
    state: started
