---
# Create directory if it doesn't exist
- name: Make sure the log,pid folder exists.
  file:
    path: "{{ item | dirname }}"
    state: directory
    owner: "{{ zabbix_user | default('zabbix') }}"
    group: "{{ zabbix_user | default('zabbix') }}"
    mode: 0755
  loop:
    - "{{ zabbix_basedir }}{{ zabbix_agentd_LogFile }}"
    - "{{ zabbix_basedir }}{{ zabbix_agentd_PidFile }}"

# Setup configuration parameters.
- name: Update zabbix agent default configure file "zabbix_agentd.conf"
  template:
    src: zabbix_agentd.conf.j2
    dest: "{{ zabbix_basedir }}/etc/zabbix_agentd.conf"
